window.SUPABASE_URL =
  "https://hzmxqihbmiyivnbujelt.supabase.co";

window.SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bXhxaWhibWl5aXZuYnVqZWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3MjcxMDMsImV4cCI6MjEwNDMwMzEwM30.HRHO4AgrUFmNQ6eNSl6XVMSqwKHlqv6cC15_1uSzITw";
